### ISSUE TITLE
Can we have a setter method with and without animated to set the stepper slider position

### ISSUE THREAD

**Issue by vickyrappier** [spromicky/StepSlider#1]
Can we have a setter method with and without animated to set the stepper slider position

Same like the moveto if it can work after initialising component and with animation allowed.

**Comment by spromicky** [comment]
Hi, i understood about setter and agree, that it make sense. But what does you mean with initialising? Do you wanna to init `StepSlider` with some `animated` property?

**Comment by vickyrappier** [comment]
I am creating this to use as the XIB way of initialisation, Also making some changes in the files to achieve this.

But issue is the components is all drawn from the top left corner and hence have issues to add as subview and do lot of manual coding. I attached your component as updated work changes. Please help me if we can achieve this.

[Archive.zip](https://github.com/spromicky/StepSlider/files/142352/Archive.zip)

**Comment by spromicky** [comment]
@vickyrappier i'm add possibility to change `StepSlider`'s index animated with method `setIndex:animated:`. It's works like a charm. ;)
And about your archive: i don't understand where you get this component, but it is not mine. Sorry, but have not time to see intro your component and fix your issue.
But you always can do pull request for this `StepSlider` to improve it.

**Comment by vickyrappier** [comment]
"@vickyrappier i'm add possibility to change StepSlider's index animated with method setIndex:animated:. It's works like a charm. ;)
" Can u like to share this animated movement at time of first display using set index: function you used.

**Comment by spromicky** [comment]
If i understood correctly, you wanna to change slider position from default to some position animated, when it appear on screen. You already can do this. 
For example if you wanna do it, when view controller that contain this `StepSlider`, appear. You init `StepSlider` from XIB or from somewhere in code and then in `viewDidAppear:` do animated change:
``` objective-c
- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    [self.slider setIndex:self.sliderPosition animated:YES];
}
```

But you can not init and immediately change StepSlider's index like this: 
``` objective-c
- (void)someUserAction:(id)sender
{
    StepSlider *slider = [[StepSlider alloc] init];
    [self.view addSubview:self.slider];
    [self.slider setIndex:someIndex animated:YES];
}
```
Because `layoutSubviews` not triggered yet. And instant call `setIndex:Animated` just ruine it. 
I'll try to fix it.

**Comment by vickyrappier** [comment]
Great , let me try this and real thanks for your guidance out of your busy schedule.

Also i face one small issue when you drag the slider with 4 points stepper to extreme end its pulled back a bit up from slider bar to starting 0th position some pan drag offset issue.

**Comment by spromicky** [comment]
I investigated second case, when you try animated component immediately after `init`. I looked at `UISwitch`. I repeated the same code for `UISwitch`.  And i got unexpected behaviour: 
![animated](https://cloud.githubusercontent.com/assets/3592457/13352589/ebfc899c-dc96-11e5-8905-2ef2cc3716cd.gif)
``` objective-c
    if (!self.switchControl) {
        self.switchControl = [[UISwitch alloc] init];
        self.switchControl.center = self.view.center;
        [self.view addSubview:self.switchControl];
    }
    [self.switchControl setOn:YES animated:YES];
```
And no such behaviour for not animated case:
![not_animated](https://cloud.githubusercontent.com/assets/3592457/13352640/3cf75ab6-dc97-11e5-8f1b-e36ae60605e6.gif)
``` objective-c
    [self.switchControl setOn:YES animated:NO];
```
So I decided to leave it as it is in current version. Maybe not the best behaviour, but still as Apple's native components behaviour.

>Also i face one small issue when you drag the slider with 4 points stepper to extreme end its pulled back a bit up from slider bar to starting 0th position some pan drag offset issue.

Can not reproduce. Can you give more detail or show this?
