### ISSUE TITLE
Slider not drawing when it's bounds size is float with decimals

### ISSUE THREAD

**Issue by Shebuka** [spromicky/StepSlider#10]
As title says when, as result of constraints, the bounds size of the control has some decimals like `boundsSize = (width = 322.66666666666663, height = 44)` the resulting contentSize will be something like `contentSize = (width = 322.66665649414063, height = 44)`, `CGSizeEqualToSize` on [Line 145](https://github.com/spromicky/StepSlider/blob/master/StepSlider/source/StepSlider/StepSlider.m#L145) will always fail and the code will `return` on [Line 148](https://github.com/spromicky/StepSlider/blob/master/StepSlider/source/StepSlider/StepSlider.m#L148) without drawing anything.

**Comment by Shebuka** [comment]
Same behaviour if we add a height constraint, e.g. 82.

**Comment by spromicky** [comment]
Same as #11.
