### ISSUE TITLE
if using the masonry to layout StepSlider, you will cant find the slider in your view

### ISSUE THREAD

**Issue by YanCeyMichael** [spromicky/StepSlider#11]
Hi, here some problems to use your StepSlider by using the masonry to layout, you will cant find the slider and the labels in your StepSlider on the UI, and cant you tell me how to solve the problems?

**Comment by jcarroll-mediafly** [comment]
Hi there. While I can't confirm, if you ran into the problem I did this may help. 

StepSlider has an intrinsic size. Much like apple's slider. When you use auto-layout with StepSlider you just have ensure it has x,y values (centering, align edges, whatever) and an width. StepSlider will figure out its own height. If you set the height yourself, StepSlider won't render.

Hope this helps

**Comment by spromicky** [comment]
Yep, @jcarroll-mediafly was right. It's all about trying be like Apple's controls. Now fixed it and height constraint does not ruin render process.
