### ISSUE TITLE
[Question] How to custom multiple colors with Label  ?

### ISSUE THREAD

**Issue by chihung93** [spromicky/StepSlider#13]
<img width="683" alt="screen shot 2017-07-19 at 6 03 23 pm" src="https://user-images.githubusercontent.com/5199109/28363930-9d3d7580-6cac-11e7-8d4b-181a5b6fe02d.png">

I wanna custom like this with your libs.
So what can I change for that ?

**Comment by spromicky** [comment]
Hi! In current version you can customize slider to this:
![screen shot 2017-07-20 at 12 26 06](https://user-images.githubusercontent.com/3592457/28410582-c43dbc9a-6d46-11e7-98c0-5f659b990f67.png)
But for drawing a lines you need to fork and write some code for this. Hope I helped you.
