### ISSUE TITLE
Customise label height in Objective C

### ISSUE THREAD

**Issue by Mamtak1811** [spromicky/StepSlider#14]
I want each label to have text as "Order Recieved", "Placed at Restaurant", etc. These are relatively bigger labels so they should be set to 0 lines so that they can be viewed in the same width as allocated but text should be on multiple lines so as to view whole text. How is that possible?

**Comment by spromicky** [comment]
It's needs improvements for such case. I'll do it in next release. Or if you want you can contribute this changes.

**Comment by Macbiont** [comment]
@Mamtak1811 did you already implement multiline CATextLayers?

**Comment by Mamtak1811** [comment]
@Macboint No, I haven't implemented multiline labels. I reduced the required text to be shown in each label instead.

**Comment by spromicky** [comment]
Implemented in 1.1.0 release.
