### ISSUE TITLE
Hello, I want to set  Slider minimumValueImage and maximumValueImage

### ISSUE THREAD

**Issue by Levofloxacin** [spromicky/StepSlider#15]
please tell me how to set it.

**Comment by spromicky** [comment]
I don't clearly understand what does you mean. StepSlider doesn't have any property like `minimumValueImage` or `maximumValueImage`. Can you explain in details?

**Comment by Levofloxacin** [comment]
I mean set sliderBar image.. just like..

 UISlider.h
@property(nullable, nonatomic,strong) UIImage *minimumValueImage;          // default is nil. image that appears to left of control (e.g. speaker off)
@property(nullable, nonatomic,strong) UIImage *maximumValueImage;          // default is nil. image that appears to right of control (e.g. speaker max)


 set property minimumValueImage or maximum valueImage
Sorry, my English is very bad can't too much description in details

i hope you can understand

thanks..

**Comment by spromicky** [comment]
Thanks for answer. StepSlider does not have possibility to easy customize or implement like this. I think, this is will add unnecessary complexity. But you feel free to fork and implement this for your use.
