### ISSUE TITLE
If maxCount = 1, it'll crash.

### ISSUE THREAD

**Issue by lxszl** [spromicky/StepSlider#2]
Hello, thanks for your great job .but I found a bug, If maxCount = 1, it'll crash.

**Comment by spromicky** [comment]
@lxszl thanks you for pointing out the crash. But setting `maxCount` to `1` still make no sense. So I just clarified this moment in documentation and added `NSAssert` for more information, why crash was caused.

**Comment by lxszl** [comment]
I fetch something from sqlite to show in pages,the maxCount was set automatically,it maybe 1...

Thank you.
