### ISSUE TITLE
How can i set seperate image on track circle and slider circle?

### ISSUE THREAD

**Issue by hardikamal** [spromicky/StepSlider#20]
Thanks for the great library.
I have one query that I want to achieve something like this (https://github.com/sujithkanna/SmileyRating) but I am not able to track on how to set the separate image on track circle and slider circle?
Please see if you could help me on this.

Thanks

**Comment by spromicky** [comment]
Thanks! For now you can't set image for track circles. But it's implemented in #17. You can clone it stade alone, or finish the example and i'll accept this PR and will make new version with this feature.

**Comment by hardikamal** [comment]
@spromicky I have tried that clone but I am not able to set seperate track image, all i can set is one image on all the track circle. So could you plz guide me with how I can set.

Thanks

**Comment by spromicky** [comment]
Oh sure only one image for all, thats my mistake. Then you can't do the same slider, as your example. You can use code from #17, little bit modify and get what you need. You just need add an array for track images and set image for track circle by index.
