### ISSUE TITLE
Crashed when sliding between two values rapidly

### ISSUE THREAD

**Issue by hezhk3** [spromicky/StepSlider#21]
It crashed when I slide between two values rapidly. It can be reproduced.

![image](https://user-images.githubusercontent.com/18214217/41702373-7d7e27e8-7562-11e8-93bc-2af2f8ce66e6.png)

**Comment by spromicky** [comment]
Can't reproduce. Can you provide some more information, like steps or environment?

**Comment by daemelchi** [comment]
I am seeing the same issue - everything is current (iOS version, pod version 1.3). It's not a high priority as the user is basically 'toying' with the application if this happens, but it crashes is they are switching values quickly. For example I have 0-5 as options. If the user taps on 1, 3, 1, 3 continuously then the app will crash on line 287. The console displays "-[Not A Type isEqual:]: message sent to deallocated instance "
<img width="1117" alt="screen shot 2018-12-17 at 8 01 42 pm" src="https://user-images.githubusercontent.com/1718810/50125401-b2a29600-0236-11e9-8962-5bd49b9658bb.png">

**Comment by cpf008** [comment]
I have same qusition.  Its easy to reproduce, just quick click， back to back and crash。

**Comment by davcpas1234** [comment]
@spromicky steps to reproduce:
1. setup a step slider with 5 steps (1, 2, 3, 4, 5)
2. set the slider to update tint color on `UIControlEvent.valueChange` based on returned index value 
3. run the app
4. select index 5, as the change is animating, attempt to drag the circle to a new index
5. crash observed

Example GIF:
![stepslidercrash](https://user-images.githubusercontent.com/3764587/56743543-a8595100-676e-11e9-84ef-6f062986ba3a.gif)

**Comment by spromicky** [comment]
Thanks for great report! Will try to fix this in next week.

**Comment by knothed** [comment]
Did you fix it?

**Comment by cpf008** [comment]
Remove the animation part of the code can be solved




| |
xiaocui
|
|
邮箱：xiaocui_008@126.com
|

Signature is customized by Netease Mail Master

On 08/23/2019 20:09, David wrote:

Did you fix it?

**Comment by spromicky** [comment]
After a long week crash fixed in `1.5.0`. Also improve animation for circles.

**Comment by cpf008** [comment]
thanks very much




| |
xiaocui
|
|
邮箱：xiaocui_008@126.com
|

Signature is customized by Netease Mail Master

On 09/19/2019 23:18, spromicky wrote:

Closed #21.
