### ISSUE TITLE
Not working on Xcode 10.1/ iOS 12.1

### ISSUE THREAD

**Issue by CHOIMINSEOK** [spromicky/StepSlider#27]

**Comment by spromicky** [comment]
Can you provide more information about what exactly not working?

**Comment by CHOIMINSEOK** [comment]
It shows up in Interface Builder, but I couldn't find it on app.

**Comment by spromicky** [comment]
Can you reproduce this in example from this repository? Or this is only reproduced in your app? If it's possible only in your app, can you show how you use this in app? Maybe some specific use or corner case?

**Comment by CHOIMINSEOK** [comment]
Have you tried this on Swift Project? 

I also tried on new empty project, but same happened
