### ISSUE TITLE
Slider image displayed unscaled on different phones

### ISSUE THREAD

**Issue by jbushyhead** [spromicky/StepSlider#28]
I am using an image for my slider handle and noticed that sometimes StepSlider will display the handle at a normal, scaled resolution and sometimes display it at full resolution. This seems to depend on what phone you're using. Here is a screenshot of some different simulators: https://ibb.co/TYB5JJV. You'll notice that on the XR (12.1), 5s (12.1), and 5s (11.2) the handle is bigger than on the X (12.1) and X (11.2). I have a sample project (here: https://www.dropbox.com/s/f4aor6t43qtr1vq/StepSliderBugTest.zip?dl=0) if you'd like to try and reproduce yourself. I've looked into this myself but I can't see anything wrong with your code.

**Comment by spromicky** [comment]
Thanks for contribution! Just add @2x resources for @2x devices. This will fix your problem.

**Comment by jbushyhead** [comment]
Thanks for your help!
