### ISSUE TITLE
how to disable changing value then I clicked slider?

### ISSUE THREAD

**Issue by bizibizi** [spromicky/StepSlider#3]
I made it like that:

- (BOOL)beginTrackingWithTouch:(UITouch *)touch withEvent:(UIEvent *)event
{
    startTouchPosition = [touch locationInView:self];
    startSliderPosition = _sliderCircleLayer.position;
    
    if (CGRectContainsPoint(_sliderCircleLayer.frame, startTouchPosition)) {
        return YES;
    } else {
//        for (NSUInteger i = 0; i < _trackCirclesArray.count; i++) {
//            CALayer *dot = _trackCirclesArray[i];
//            
//            CGFloat dotRadiusDiff = 22 - self.trackCircleRadius;
//            CGRect frameToCheck = dotRadiusDiff > 0 ? CGRectInset(dot.frame, -dotRadiusDiff, -dotRadiusDiff) : dot.frame;
//            
//            if (CGRectContainsPoint(frameToCheck, startTouchPosition)) {
//                NSUInteger oldIndex = _index;
//                
//                _index = i;
//                
//                if (oldIndex != _index) {
//                    [self sendActionsForControlEvents:UIControlEventValueChanged];
//                }
//                animateLayouts = YES;
//                [self setNeedsLayout];
//                return NO;
//            }
//        }
    }
    return NO;
}

will be great if you can add that feature

**Comment by spromicky** [comment]
Hi! On first look it's seems right. I will look to add property, that can turn off `tap on dot` behaviour by default.

**Comment by spromicky** [comment]
I added new property `dotsInteractionEnabled`. Now you can set it to `NO` and will turn on behaviour, that you want. And I pushed new `0.1.4` version to CocoaPods.

**Comment by bizibizi** [comment]
great, thanks
