### ISSUE TITLE
Slider is not showing custom 'trackColor'.

### ISSUE THREAD

**Issue by NabeelHayat** [spromicky/StepSlider#37]
Slider shows only track dots and tracker image but tracker path color is not showing i think it's transparent, check attach file no tracker line. Please help me what i'm missing?
![slider](https://user-images.githubusercontent.com/11197291/64471112-5259d880-d166-11e9-8221-fb9f95163ae5.png)

My code is here:

self.speedSlider.maxCount = 5
self.speedSlider.index = 2
self.speedSlider.trackCircleRadius = 5.0
self.speedSlider.isDotsInteractionEnabled = true
self.speedSlider.trackColor = Colors.trackColor
self.speedSlider.sliderCircleImage = UIImage(named: "edit_speedeffect_icon2")
self.speedSlider.sliderCircleImage = UIImage(named: "edit_speedeffect_icon1")
self.speedSlider.labelColor = Colors.primary
self.speedSlider.labelOrientation = StepSliderTextOrientation.up
self.speedSlider.labels = self.rateSliderStringValues
self.speedSlider.labelFont = Fonts.Light.of(size: 14)

I'm using Swift 4.0 with XCode 10.3.

**Comment by spromicky** [comment]
Not sure how you initialize the slider, but i think that [trackHeight](https://github.com/spromicky/StepSlider/blob/master/StepSlider/source/StepSlider/StepSlider.h#L50) is wrong. Look up this property of your slider and make sure you don't set it to zero, or change it to something > 0 in this batch of code.

**Comment by NabeelHayat** [comment]
Thanks for helping @spromicky when i'm setting trackHeight greater than 20 its work for me. I don't know why but its work for me thanks.
