### ISSUE TITLE
Can we enable dotsInteractionEnabled and Slider both at the same time?

### ISSUE THREAD

**Issue by Pratik948** [spromicky/StepSlider#4]
This is a feature request!
is it possible to enable both dot interaction and sliding? means that user can directly select a dot or can slide from a dot to another one?

**Comment by Pratik948** [comment]
Duplicate? :(

**Comment by spromicky** [comment]
Hi. This feature is already released in #3 and version `0.1.4`. You can set `dotsInteractionEnabled` property in `YES` to enable both: dots and sliding interaction. And `NO` to disable dots interaction.
Slide interaction is base and can't be disabled.
