### ISSUE TITLE
Sliding not working when adding Stepslider in a View Controller with Presentation style as Automatic or Page Sheet

### ISSUE THREAD

**Issue by Kavisha-Dev** [spromicky/StepSlider#40]
Steps to reproduce:

1. Create a View Controller, add view and set the class as your Stepslider.
2. Set the Presentation of the View Controller as Automatic or Page Sheet so that it partially covers the screen (new in iOS 13)
3. Now run the project and Try sliding the slider - It does not slide smoothly. Although touching the points in between causes the slider to move
4. This problem does not occur when the View Controller is presented fully (As Full Screen).

If it helps, i have created a repo with the above issue.  
https://github.com/Kavisha-Dev/TestStepSliderSimpleVC.

Request your help here. Thanks!

**Comment by martin1612** [comment]
Facing with the same issue - any solution on that?

**Comment by Kavisha-Dev** [comment]
@martin1612 No, not yet. :/

**Comment by martin1612** [comment]
@Kavisha-Dev  I have created a pull request - take a look :)

**Comment by spromicky** [comment]
Fixed in version 1.6.0.

**Comment by Kavisha-Dev** [comment]
Sorry for the delay and thank you so much for the fix @martin1612 . I actually had gone ahead and made the view controller fullscreen to avoid the issue.

Thank you so much @spromicky for the wonderful library.
