### ISSUE TITLE
iOS 14 Circle(Thumb) image issue

### ISSUE THREAD

**Issue by sacred0x01** [spromicky/StepSlider#47]
With current beta 7 of iOS 14 library faced with issue right after touch end:
when update layout started with `animateLayouts = YES;`
Each time it shows additional resources from asset catalog (but same each time).
Hope it's only iOS 14 beta issue but rather strange

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/58253926/92483580-a839e400-f1f1-11ea-97e9-2cead0100599.gif)

Temp solution for now
```swift
- (void)endTouches
{  
...  
    if (@available(iOS 14, *)) {
        animateLayouts = NO;
    } 
...
}
```

**Comment by spromicky** [comment]
Can you provide sample project to reproduce this issue?

**Comment by sacred0x01** [comment]
@spromicky 
[SliderTest.zip](https://github.com/spromicky/StepSlider/files/5188796/SliderTest.zip)

Got the same result.
Gonna try some resources variants (pdf vs png) - no luck.

**Comment by spromicky** [comment]
Thanks, i'll take a look.

**Comment by LEEKIWAN** [comment]
<img width="1115" alt="스크린샷 2020-09-25 오전 11 09 12" src="https://user-images.githubusercontent.com/30687224/94218494-8ba2e900-ff1f-11ea-9167-58dc6e991392.png">

Scales -> Single Scale 

It temporary Works

**Comment by spromicky** [comment]
Fix will be released with 1.8.0 version.

**Comment by sacred0x01** [comment]
Thanks, i think it was really strange bug)

**Comment by spromicky** [comment]
Yep, already released btw.
