### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by dimohamdy** [spromicky/StepSlider#5]
I begin convert code to swift but i have problem to convet this code

```
#define GENERATE_SETTER(PROPERTY, TYPE, SETTER, UPDATER) \
- (void)SETTER:(TYPE)PROPERTY { \
    if (_##PROPERTY != PROPERTY) { \
        _##PROPERTY = PROPERTY; \
        UPDATER \
        [self setNeedsLayout]; \
    } \
}
```

can you help me to convert it?
you can check my code in this forked repo in swift branch 
https://github.com/dimohamdy/StepSlider

**Comment by spromicky** [comment]
I do not understand why you wanna convert it to swift, where is profit? But if you want - do it.
This code is precompile macro and it converts to usual setter, when compile. I wrote it just for less code and DRY. So you can use `willSet` for all those properties in swift. So code for `index` will be looks like:
```swift
var index = 0 {
    willSet {
        guard newValue != index else { return }
            
        sendActionsForControlEvents(.ValueChanged)
        setNeedsLayout()
    }
}
```

**Comment by dimohamdy** [comment]
thank you
