### ISSUE TITLE
Reduce space between labels and slider

### ISSUE THREAD

**Issue by paul-lavoine** [spromicky/StepSlider#51]
Hello,

I find there is a lot of space between labels and slider. Is it one way to reduce it ?

<img width="718" alt="Screenshot 2021-01-27 at 13 10 52" src="https://user-images.githubusercontent.com/8981703/105989476-7989b080-60a1-11eb-9fec-a97c3a96065f.png">

**Comment by spromicky** [comment]
Hi, sure. Change `labelOffset` property as you wish. Default value is `20`.

**Comment by paul-lavoine** [comment]
Ho great! I didn't see it!
Thanks :)
