### ISSUE TITLE
How to change the alpha color of the bar before the slider circle ?

### ISSUE THREAD

**Issue by Rocail** [spromicky/StepSlider#55]
Hello,

My goal is to have a color with an alpha value in the section before the sliderCircle

I tried to play around the tintColor, but I had the following behavior:

When you set a tint color it changes the color of the bar before the thumb, but if you set an UIColor with alpha the display color ignores the alpha channel

The following code:
```swift
self.slider.maxCount = 5
self.slider.tintColor = UIColor.blue.withAlphaComponent(0.2)
self.slider.trackColor = UIColor.blue
self.slider.sliderCircleColor = UIColor.blue
```
looks like this:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/14996372/150955270-83808618-84e9-4dc0-af23-dedf6cff54b3.png">

What i would like to do is basically the reverse of this:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/14996372/150955942-5ee42c38-706a-47d6-9170-e56c33797a1e.png">
which uses the following code:
```swift
self.slider.maxCount = 5
self.slider.tintColor = UIColor.blue
self.slider.trackColor = UIColor.blue.withAlphaComponent(0.2)
self.slider.sliderCircleColor = UIColor.blue
```

BTW, the ending section of the bar & the slider circles doesn't seems to have exactly the same color despite having exactly the same UIColor set ... is it normal ?

**Comment by spromicky** [comment]
Hi, currently it's not possible, because of layer hierarchy. For now to draw this control I draw a track layer and some circles over it. So you will get overlapping anyway. 

To solve this problem you need to draw track and circles on it as one layer.

> BTW, the ending section of the bar & the slider circles doesn't seems to have exactly the same color despite having exactly the same UIColor set ... is it normal ?

Yes, two layers with same color with alpha in blend will be a little bit darker.
