### ISSUE TITLE
add label on top of each index

### ISSUE THREAD

**Issue by dimohamdy** [spromicky/StepSlider#6]
how can i add label on top of each Circle ?

**Comment by spromicky** [comment]
There is no such functional. But if need that you can do it and create pull request. All of `StepSlider` users will be grateful to you. Or leave issue open and I will do it by myself in future.

**Comment by dimohamdy** [comment]
@spromicky  please accept my pull request 
https://github.com/spromicky/StepSlider/pull/7

**Comment by JamesHarlin** [comment]
Hi dimohamdy, awesome idea about the labels, I just checked it out. It appears the labels get duplicated after device rotation. I'm trying to figure it out but thought I'd let you know in the meantime

**Comment by dimohamdy** [comment]
i will update it to set array of text to set in labels and i will check the bug of rotation

**Comment by dimohamdy** [comment]
@JamesHarlin  I fix bug of dublicate labels when rotate

**Comment by JamesHarlin** [comment]
@dimohamdy Just tried it out, works great, thanks.

**Comment by dimohamdy** [comment]
@spromicky please review code and accept pull request ☺

**Comment by spromicky** [comment]
Implemented in [1.0.0](https://github.com/spromicky/StepSlider/releases/tag/1.0.0).

**Comment by dimohamdy** [comment]
@spromicky Thanks and don't forget to update demo  :v:

**Comment by spromicky** [comment]
@dimohamdy demo is updated too.
