### ISSUE TITLE
Setter of some properties doesn't works

### ISSUE THREAD

**Issue by blueshunter** [spromicky/StepSlider#9]
Trying to update sliderCircleRadius, trackCircleRadius and trackHeight properties cause a issue .Slider view do not appears on subview after setting properties

PS : the corresponding getters works fine

**Comment by spromicky** [comment]
Hmmm... Really strange behaviour. Will be great if you share some code example of your usage. And version of `StepSlider`.

**Comment by blueshunter** [comment]
Hi, i do some tests : I was wrong about getter methods issue, the problem on my project is the the component frame. If the width is lesser than 240.0f, the component does not appears. An code example below : 
`
    CGRect validRect = CGRectMake(10.f, 240.f, 300.f, 44.f);
    
    CGRect invalidRect = CGRectMake(10.f, 200.f, 239.f, 44.f);
    
    StepSlider *slider = [[StepSlider alloc] initWithFrame:invalidRect];
    
    [slider setBackgroundColor:[UIColor grayColor]];
    [slider setMaxCount:4];
    [slider setIndex:1];
    [slider setAdjustLabel:YES];
    [slider setLabels:@[@"0", @"25", @"50", @"100"]];
    [slider setLabelColor:[UIColor darkTextColor]];
    [slider setDotsInteractionEnabled:YES];
    [slider setSliderCircleRadius:slider.sliderCircleRadius];
    [slider setTrackCircleRadius:slider.trackCircleRadius];
    [slider setTrackHeight:slider.trackHeight];
    [self.view addSubview:slider];
`

PS :  I'm on StepSlider 1.0.0 version

**Comment by spromicky** [comment]
I've tried your code and StepSlider still appears. But I've found some `frame` issue. I fixed this. Hope its also will fix your case. I wanna wait before push it as new version. Just wait maybe someone will find another bug. So i ask your test please, that code from `master`, and will write your result here.

**Comment by spromicky** [comment]
Push new version to CocoaPods.

**Comment by csotiriou** [comment]
After updating to version 1.0.x from 0.1.x, I am also seeing strange behaviour. There are some widths in which the slider will not appear at all.

I am using 1.0.1

**Comment by spromicky** [comment]
@csotiriou, can you provide more details? What iOS, how you use StepSlider? Will be great if you make pull request with example, when this behaviour reproduced.

**Comment by perteadrian** [comment]
I also have this problem. I added to my Swift project via Cocoapods. When I first installed the framework it didn't show in storyboard or in the testing device. I kept messing around with the visual proprieties and finally got it to work. Then I send a commit to my repo on Github and now it's again missing.

**Comment by spromicky** [comment]
Hope I fixed it in 1.0.2.
